# Generated by Django 5.0.1 on 2024-01-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('comment', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_solver', models.CharField(max_length=256)),
                ('cat_id', models.IntegerField(blank=True)),
                ('image_of_solver', models.ImageField(blank=True, null=True, upload_to='solver_image')),
                ('full_description', models.CharField(max_length=2048)),
                ('author', models.CharField(blank=True, max_length=256)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
