# Generated by Django 5.0.1 on 2024-01-25 21:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='solver_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.solver'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExInSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ex', models.IntegerField(blank=True)),
                ('text', models.CharField(blank=True, max_length=2048)),
                ('correct_answer', models.CharField(blank=True, max_length=1024)),
                ('complexity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5)])),
                ('solver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.solver')),
            ],
        ),
    ]
