# Generated by Django 5.0.1 on 2024-01-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_solver_id_exinsolver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='solver_id',
        ),
        migrations.AlterField(
            model_name='solver',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories'),
        ),
    ]
