# Generated by Django 5.0.1 on 2024-01-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_categories_solver_id_alter_solver_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exinsolver',
            old_name='solver_id',
            new_name='solver',
        ),
        migrations.RenameField(
            model_name='solver',
            old_name='cat_id',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='solver',
            old_name='image_of_solver',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='solver',
            old_name='name_of_solver',
            new_name='name',
        ),
    ]
