# Generated by Django 5.0.1 on 2024-01-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_exinsolver_solver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solver',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
        ),
    ]
